import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

const DEFAULT_PASSWORD = "password123";

const usersData = [
  { name: "Rahul Sharma", email: "rahul@example.com", mobileNo: "9876543210" },
  { name: "Priya Patel", email: "priya@example.com", mobileNo: "9876543211" },
  { name: "Amit Kumar", email: "amit@example.com", mobileNo: "9876543212" },
  { name: "Sneha Desai", email: "sneha@example.com", mobileNo: "9876543213" },
  { name: "Vikram Singh", email: "vikram@example.com", mobileNo: "9876543214" },
];

const propertiesData = [
  {
    title: "Residential Plot in Chikhli",
    listingType: "Sell",
    propertyType: "Residential",
    propertyCategories: "Plot/Land",
    city: "Buldhana",
    locality: "Chikhli",
    plotArea: "1200",
    plotAreaUnit: "sqft",
    length: "40",
    breadth: "30",
    allowedFloors: "3",
    hasBoundaryWall: true,
    openSides: "2",
    hasConstruction: false,
    possessionBy: "Immediate",
    ownership: "Freehold",
    priceTotal: 1200000,
    pricePerSQFT: 1200,
    inclusivePrice: true,
    isTaxExcluded: false,
    isPriceNegotiable: true,
    uniqueFeatures: "Corner plot, wide road access, clear title.",
    propertyFacing: "East",
    amenities: ["Water", "Electricity", "Road"],
    overlooking: ["Garden", "Main Road"],
    locationAdvantages: ["Near Market", "Near School"],
    propertyPhotos: [
      "https://placehold.co/800x600/e8e8e8/666?text=Residential+Chikhli&font=source-sans-3",
      "https://placehold.co/800x600/ddd/555?text=Plot+View&font=source-sans-3",
    ],
  },
  {
    title: "Premium Plot in Thane",
    listingType: "Sell",
    propertyType: "Residential",
    propertyCategories: "Plot/Land",
    city: "Mumbai",
    locality: "Thane",
    plotArea: "2000",
    plotAreaUnit: "sqft",
    length: "50",
    breadth: "40",
    allowedFloors: "4",
    hasBoundaryWall: true,
    openSides: "3",
    hasConstruction: false,
    possessionBy: "Within 6 months",
    ownership: "Freehold",
    priceTotal: 4500000,
    pricePerSQFT: 2250,
    inclusivePrice: false,
    isTaxExcluded: true,
    isPriceNegotiable: true,
    uniqueFeatures: "Gated layout, near highway, ready for construction.",
    propertyFacing: "North",
    amenities: ["Water", "Electricity", "Road", "Drainage"],
    overlooking: ["Park", "Highway"],
    locationAdvantages: ["Near Metro", "Near Hospital", "Schools nearby"],
    propertyPhotos: [
      "https://placehold.co/800x600/e0e0e0/555?text=Thane+Plot&font=source-sans-3",
    ],
  },
  {
    title: "Commercial Plot in Panvel",
    listingType: "Sell",
    propertyType: "Commercial",
    propertyCategories: "Plot/Land",
    city: "Navi Mumbai",
    locality: "Panvel",
    plotArea: "5000",
    plotAreaUnit: "sqft",
    length: "100",
    breadth: "50",
    allowedFloors: "G+3",
    hasBoundaryWall: false,
    openSides: "2",
    hasConstruction: false,
    possessionBy: "Immediate",
    ownership: "Leasehold",
    priceTotal: 12500000,
    pricePerSQFT: 2500,
    inclusivePrice: false,
    isTaxExcluded: false,
    isPriceNegotiable: false,
    uniqueFeatures: "Highway front, ideal for showroom or warehouse.",
    propertyFacing: "West",
    amenities: ["Water", "Electricity", "Road", "Drainage"],
    overlooking: ["Highway", "Open"],
    locationAdvantages: ["NH-48", "Near Airport", "Industrial zone"],
    propertyPhotos: [
      "https://placehold.co/800x600/d5d5d5/444?text=Commercial+Panvel&font=source-sans-3",
    ],
  },
  {
    title: "Residential Plot in Uran",
    listingType: "Sell",
    propertyType: "Residential",
    propertyCategories: "Plot/Land",
    city: "Navi Mumbai",
    locality: "Uran",
    plotArea: "1500",
    plotAreaUnit: "sqft",
    length: "50",
    breadth: "30",
    allowedFloors: "3",
    hasBoundaryWall: true,
    openSides: "2",
    hasConstruction: false,
    possessionBy: "Immediate",
    ownership: "Freehold",
    priceTotal: 2100000,
    pricePerSQFT: 1400,
    inclusivePrice: true,
    isTaxExcluded: false,
    isPriceNegotiable: true,
    uniqueFeatures: "Near Navi Mumbai Airport, appreciating location.",
    propertyFacing: "South",
    amenities: ["Water", "Electricity", "Road"],
    overlooking: ["Open", "Green"],
    locationAdvantages: ["Airport proximity", "MTHL connectivity"],
    propertyPhotos: [
      "https://placehold.co/800x600/eee/666?text=Uran+Plot&font=source-sans-3",
    ],
  },
  {
    title: "Villa Plot in Chirle",
    listingType: "Sell",
    propertyType: "Villa/bungalow",
    propertyCategories: "Plot/Land",
    city: "Third Mumbai",
    locality: "Chirle",
    plotArea: "3000",
    plotAreaUnit: "sqft",
    length: "60",
    breadth: "50",
    allowedFloors: "2",
    hasBoundaryWall: true,
    openSides: "4",
    hasConstruction: false,
    possessionBy: "Within 1 year",
    ownership: "Freehold",
    priceTotal: 7200000,
    pricePerSQFT: 2400,
    inclusivePrice: false,
    isTaxExcluded: true,
    isPriceNegotiable: true,
    uniqueFeatures: "Hill view, peaceful locality, villa-ready layout.",
    propertyFacing: "East",
    amenities: ["Water", "Electricity", "Road", "Drainage"],
    overlooking: ["Hill", "Garden"],
    locationAdvantages: ["Scenic", "Low density", "Good connectivity"],
    propertyPhotos: [
      "https://placehold.co/800x600/e5e5e5/555?text=Villa+Chirle&font=source-sans-3",
    ],
  },
  {
    title: "Affordable Plot in Ranjanpada",
    listingType: "Sell",
    propertyType: "Residential",
    propertyCategories: "Plot/Land",
    city: "Navi Mumbai",
    locality: "Ranjanpada",
    plotArea: "1000",
    plotAreaUnit: "sqft",
    length: "40",
    breadth: "25",
    allowedFloors: "3",
    hasBoundaryWall: false,
    openSides: "2",
    hasConstruction: false,
    possessionBy: "Immediate",
    ownership: "Freehold",
    priceTotal: 950000,
    pricePerSQFT: 950,
    inclusivePrice: true,
    isTaxExcluded: false,
    isPriceNegotiable: true,
    uniqueFeatures: "Budget-friendly, clear title, easy loan approval.",
    propertyFacing: "North",
    amenities: ["Water", "Electricity", "Road"],
    overlooking: ["Road"],
    locationAdvantages: ["Affordable", "Growing area"],
    propertyPhotos: [
      "https://placehold.co/800x600/dedede/444?text=Ranjanpada&font=source-sans-3",
    ],
  },
  {
    title: "Investment Plot in Vindhane",
    listingType: "Sell",
    propertyType: "Residential",
    propertyCategories: "Plot/Land",
    city: "Navi Mumbai",
    locality: "Vindhane",
    plotArea: "1800",
    plotAreaUnit: "sqft",
    length: "45",
    breadth: "40",
    allowedFloors: "3",
    hasBoundaryWall: true,
    openSides: "2",
    hasConstruction: false,
    possessionBy: "Immediate",
    ownership: "Freehold",
    priceTotal: 2700000,
    pricePerSQFT: 1500,
    inclusivePrice: true,
    isTaxExcluded: false,
    isPriceNegotiable: true,
    uniqueFeatures: "High appreciation potential, near upcoming infra.",
    propertyFacing: "East",
    amenities: ["Water", "Electricity", "Road"],
    overlooking: ["Open", "Road"],
    locationAdvantages: ["Investment hotspot", "Infrastructure growth"],
    propertyPhotos: [
      "https://placehold.co/800x600/e8e8e8/555?text=Vindhane&font=source-sans-3",
    ],
  },
  {
    title: "Corner Plot in Karjat",
    listingType: "Sell",
    propertyType: "Residential",
    propertyCategories: "Plot/Land",
    city: "Mumbai",
    locality: "Karjat",
    plotArea: "2400",
    plotAreaUnit: "sqft",
    length: "60",
    breadth: "40",
    allowedFloors: "3",
    hasBoundaryWall: true,
    openSides: "3",
    hasConstruction: false,
    possessionBy: "Immediate",
    ownership: "Freehold",
    priceTotal: 2880000,
    pricePerSQFT: 1200,
    inclusivePrice: true,
    isTaxExcluded: false,
    isPriceNegotiable: true,
    uniqueFeatures: "Corner plot, three open sides, highway visibility.",
    propertyFacing: "South",
    amenities: ["Water", "Electricity", "Road"],
    overlooking: ["Highway", "Open"],
    locationAdvantages: ["Mumbai-Pune Highway", "Karjat station"],
    propertyPhotos: [
      "https://placehold.co/800x600/d8d8d8/444?text=Karjat+Plot&font=source-sans-3",
    ],
  },
  {
    title: "Flat in Thane",
    listingType: "Sell",
    propertyType: "Residential",
    propertyCategories: "Flat/Apartment",
    city: "Mumbai",
    locality: "Thane",
    plotArea: "1100",
    plotAreaUnit: "sqft",
    length: "0",
    breadth: "0",
    allowedFloors: "1",
    hasBoundaryWall: false,
    openSides: "0",
    hasConstruction: true,
    possessionBy: "Immediate",
    ownership: "Freehold",
    priceTotal: 8800000,
    pricePerSQFT: 8000,
    inclusivePrice: false,
    isTaxExcluded: false,
    isPriceNegotiable: true,
    uniqueFeatures: "2 BHK ready to move, premium society.",
    propertyFacing: "East",
    amenities: ["Water", "Electricity", "Lift", "Parking", "Security"],
    overlooking: ["Garden", "Pool"],
    locationAdvantages: ["Metro", "Malls", "Schools"],
    propertyPhotos: [
      "https://placehold.co/800x600/ebebeb/666?text=2BHK+Thane&font=source-sans-3",
    ],
  },
  {
    title: "Farmhouse Plot Near Panvel",
    listingType: "Rent/Lease",
    propertyType: "Villa/bungalow",
    propertyCategories: "Farmhouse",
    city: "Navi Mumbai",
    locality: "Panvel",
    plotArea: "10000",
    plotAreaUnit: "sqft",
    length: "100",
    breadth: "100",
    allowedFloors: "2",
    hasBoundaryWall: true,
    openSides: "4",
    hasConstruction: false,
    possessionBy: "Immediate",
    ownership: "Freehold",
    priceTotal: 25000000,
    pricePerSQFT: 2500,
    inclusivePrice: false,
    isTaxExcluded: false,
    isPriceNegotiable: true,
    uniqueFeatures: "Large plot for farmhouse, peaceful, green.",
    propertyFacing: "North",
    amenities: ["Water", "Electricity", "Road"],
    overlooking: ["Farm", "Hill"],
    locationAdvantages: ["Weekend home", "Privacy", "Nature"],
    propertyPhotos: [
      "https://placehold.co/800x600/eee/555?text=Farmhouse&font=source-sans-3",
    ],
  },
  {
    title: "Residential Plot in Third Mumbai",
    listingType: "Sell",
    propertyType: "Residential",
    propertyCategories: "Plot/Land",
    city: "Third Mumbai",
    locality: "Third Mumbai",
    plotArea: "1600",
    plotAreaUnit: "sqft",
    length: "40",
    breadth: "40",
    allowedFloors: "3",
    hasBoundaryWall: true,
    openSides: "2",
    hasConstruction: false,
    possessionBy: "Within 6 months",
    ownership: "Freehold",
    priceTotal: 3200000,
    pricePerSQFT: 2000,
    inclusivePrice: false,
    isTaxExcluded: false,
    isPriceNegotiable: true,
    uniqueFeatures: "New township, planned development, Cidco approved.",
    propertyFacing: "East",
    amenities: ["Water", "Electricity", "Road", "Drainage"],
    overlooking: ["Park", "Road"],
    locationAdvantages: ["Township", "MTHL", "Airport"],
    propertyPhotos: [
      "https://placehold.co/800x600/e0e0e0/444?text=Third+Mumbai&font=source-sans-3",
    ],
  },
  {
    title: "Small Plot in Buldhana",
    listingType: "Sell",
    propertyType: "Residential",
    propertyCategories: "Plot/Land",
    city: "Buldhana",
    locality: "Chikhli",
    plotArea: "800",
    plotAreaUnit: "sqft",
    length: "32",
    breadth: "25",
    allowedFloors: "2",
    hasBoundaryWall: false,
    openSides: "2",
    hasConstruction: false,
    possessionBy: "Immediate",
    ownership: "Freehold",
    priceTotal: 640000,
    pricePerSQFT: 800,
    inclusivePrice: true,
    isTaxExcluded: false,
    isPriceNegotiable: true,
    uniqueFeatures: "Entry-level plot, ideal for first home.",
    propertyFacing: "North",
    amenities: ["Water", "Road"],
    overlooking: ["Road"],
    locationAdvantages: ["Affordable", "Rural calm"],
    propertyPhotos: [
      "https://placehold.co/800x600/ddd/666?text=Buldhana&font=source-sans-3",
    ],
  },
  {
    title: "Warehouse Plot in Uran",
    listingType: "Sell",
    propertyType: "Commercial",
    propertyCategories: "Plot/Land",
    city: "Navi Mumbai",
    locality: "Uran",
    plotArea: "8000",
    plotAreaUnit: "sqft",
    length: "100",
    breadth: "80",
    allowedFloors: "G+2",
    hasBoundaryWall: true,
    openSides: "2",
    hasConstruction: false,
    possessionBy: "Immediate",
    ownership: "Freehold",
    priceTotal: 16000000,
    pricePerSQFT: 2000,
    inclusivePrice: false,
    isTaxExcluded: false,
    isPriceNegotiable: false,
    uniqueFeatures: "Port proximity, logistics hub, heavy vehicle access.",
    propertyFacing: "West",
    amenities: ["Water", "Electricity", "Road", "Drainage"],
    overlooking: ["Port", "Highway"],
    locationAdvantages: ["JNPT", "Port", "Export zone"],
    propertyPhotos: [
      "https://placehold.co/800x600/e5e5e5/555?text=Warehouse&font=source-sans-3",
    ],
  },
  {
    title: "Residential Plot in Ranjanpada",
    listingType: "Sell",
    propertyType: "Residential",
    propertyCategories: "Plot/Land",
    city: "Navi Mumbai",
    locality: "Ranjanpada",
    plotArea: "2200",
    plotAreaUnit: "sqft",
    length: "55",
    breadth: "40",
    allowedFloors: "3",
    hasBoundaryWall: true,
    openSides: "2",
    hasConstruction: false,
    possessionBy: "Immediate",
    ownership: "Freehold",
    priceTotal: 2860000,
    pricePerSQFT: 1300,
    inclusivePrice: true,
    isTaxExcluded: false,
    isPriceNegotiable: true,
    uniqueFeatures: "Spacious plot, good for joint family construction.",
    propertyFacing: "South",
    amenities: ["Water", "Electricity", "Road"],
    overlooking: ["Garden", "Road"],
    locationAdvantages: ["Navi Mumbai Airport", "Schools"],
    propertyPhotos: [
      "https://placehold.co/800x600/ebebeb/444?text=Ranjanpada+2&font=source-sans-3",
    ],
  },
  {
    title: "Bungalow Plot in Panvel",
    listingType: "Sell",
    propertyType: "Villa/bungalow",
    propertyCategories: "Plot/Land",
    city: "Navi Mumbai",
    locality: "Panvel",
    plotArea: "4000",
    plotAreaUnit: "sqft",
    length: "80",
    breadth: "50",
    allowedFloors: "2",
    hasBoundaryWall: true,
    openSides: "4",
    hasConstruction: false,
    possessionBy: "Within 1 year",
    ownership: "Freehold",
    priceTotal: 12000000,
    pricePerSQFT: 3000,
    inclusivePrice: false,
    isTaxExcluded: true,
    isPriceNegotiable: true,
    uniqueFeatures: "Premium bungalow plot, gated community, sea view possible.",
    propertyFacing: "East",
    amenities: ["Water", "Electricity", "Road", "Drainage"],
    overlooking: ["Garden", "Open"],
    locationAdvantages: ["Premium locality", "Connectivity", "Appreciation"],
    propertyPhotos: [
      "https://placehold.co/800x600/e8e8e8/666?text=Bungalow+Panvel&font=source-sans-3",
    ],
  },
];

async function main() {
  const passwordHash = await bcrypt.hash(DEFAULT_PASSWORD, 10);

  console.log("Seeding users...");
  const users = [];
  const adminEmail = "rahul@example.com";
  for (const u of usersData) {
    const isAdmin = u.email === adminEmail;
    const user = await prisma.user.upsert({
      where: { email: u.email },
      update: isAdmin ? { isAdmin: true } : {},
      create: {
        name: u.name,
        email: u.email,
        mobileNo: u.mobileNo,
        passwordHash,
        isAdmin,
      },
    });
    users.push(user);
  }
  console.log(`Created/updated ${users.length} users.`);

  console.log("Seeding properties...");
  let created = 0;
  for (let i = 0; i < propertiesData.length; i++) {
    const p = propertiesData[i];
    const userId = users[i % users.length].id;
    await prisma.property.upsert({
      where: { id: `seed-prop-${i + 1}` },
      update: {},
      create: {
        id: `seed-prop-${i + 1}`,
        userId,
        title: p.title,
        listingType: p.listingType,
        propertyType: p.propertyType,
        propertyCategories: p.propertyCategories,
        city: p.city,
        locality: p.locality,
        plotArea: p.plotArea,
        plotAreaUnit: p.plotAreaUnit,
        length: p.length,
        breadth: p.breadth,
        allowedFloors: p.allowedFloors,
        hasBoundaryWall: p.hasBoundaryWall,
        openSides: p.openSides,
        hasConstruction: p.hasConstruction,
        possessionBy: p.possessionBy,
        ownership: p.ownership,
        priceTotal: p.priceTotal,
        pricePerSQFT: p.pricePerSQFT,
        inclusivePrice: p.inclusivePrice,
        isTaxExcluded: p.isTaxExcluded,
        isPriceNegotiable: p.isPriceNegotiable,
        uniqueFeatures: p.uniqueFeatures,
        propertyFacing: p.propertyFacing,
        amenities: p.amenities,
        overlooking: p.overlooking,
        locationAdvantages: p.locationAdvantages,
        propertyPhotos: p.propertyPhotos,
      },
    });
    created++;
  }
  console.log(`Created/updated ${created} properties.`);

  const propertyIds = await prisma.property.findMany({ select: { id: true } }).then((r) => r.map((x) => x.id));

  console.log("Seeding website enquiries...");
  const webEnquiries = [
    { name: "Raj Mehta", email: "raj@example.com", mobile: "9123456789", message: "Interested in plots in Thane. Please share more details." },
    { name: "Kavita Nair", email: "kavita@example.com", mobile: "9123456790", message: "Looking for investment property in Navi Mumbai." },
    { name: "Arun Joshi", email: "arun@example.com", mobile: "9123456791", message: "Need a plot for building my dream home. Budget 30-40 lakhs." },
    { name: "Meera Iyer", email: "meera@example.com", mobile: "9123456792", message: "When is the next site visit for Panvel plots?" },
    { name: "Suresh Reddy", email: "suresh@example.com", mobile: "9123456793", message: "Interested in commercial plot. Please call back." },
    { name: "Anita Deshmukh", email: "anita@example.com", mobile: "9123456794", message: "Want to know about payment plans for Ranjanpada." },
    { name: "Pradeep Nambiar", email: "pradeep@example.com", mobile: "9123456795", message: "Do you have any ready-to-move plots in Uran?" },
    { name: "Lakshmi Pillai", email: "lakshmi@example.com", mobile: "9123456796", message: "Looking for farmhouse plot. Budget 1-2 Cr." },
  ];
  for (const e of webEnquiries) {
    await prisma.websiteEnquiry.create({
      data: { name: e.name, email: e.email, mobile: e.mobile, message: e.message },
    });
  }
  console.log(`Created ${webEnquiries.length} website enquiries.`);

  console.log("Seeding property enquiries...");
  for (let i = 0; i < Math.min(5, propertyIds.length); i++) {
    await prisma.propertyEnquiry.create({
      data: {
        propertyId: propertyIds[i],
        name: `Buyer ${i + 1}`,
        email: `buyer${i + 1}@example.com`,
        mobile: `987650000${i}`,
        message: `Interested in this property. Please share best price and documents.`,
      },
    });
  }
  console.log("Created 5 property enquiries.");

  console.log("Seeding property visits...");
  for (let i = 0; i < Math.min(6, propertyIds.length); i++) {
    await prisma.propertyVisit.create({
      data: {
        propertyId: propertyIds[i],
        name: `Visitor ${i + 1}`,
        email: `visitor${i + 1}@example.com`,
        mobile: `987651000${i}`,
        preferredDate: new Date(Date.now() + (i + 1) * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
        message: "Would like to schedule a site visit.",
      },
    });
  }
  console.log("Created 6 property visits.");

  console.log("Seeding homepage banners...");
  const existingBanners = await prisma.homepageBanner.count();
  if (existingBanners === 0) {
    await prisma.homepageBanner.createMany({
      data: [
        {
          title: "Zaminwale – Buying and Selling of Land",
          subtitle: "Find verified land deals with trusted sellers.",
          desktopImageUrl: "/assets/banner-img/zaminwale.avif",
          mobileImageUrl: "/assets/banner-img/zaminwale-mob.avif",
          ctaLabel: "Search",
          ctaHref: "/#search",
          sortOrder: 0,
          isActive: true,
        },
        {
          title: "99Villa – Premium Villas and Plots",
          subtitle: "Exclusive villa projects curated by Zaminwale.",
          desktopImageUrl: "/assets/banner-img/99villa.avif",
          mobileImageUrl: "/assets/banner-img/99villa-mob.avif",
          ctaLabel: "Explore 99Villa",
          ctaHref: "/about-99villa",
          sortOrder: 1,
          isActive: true,
        },
      ],
    });
    console.log("Created homepage banners.");
  } else {
    console.log("Homepage banners already exist, skipping seed.");
  }

  console.log("Seed completed successfully.");
  console.log("\nTest login: use any user email with password:", DEFAULT_PASSWORD);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
